In [1]:
import pandas as pd
import os

In [2]:
Path = "C:/Users/doosti/OneDrive - Chapman University/Research/Research Projects/Fitness/Data/"
print(Path)

C:/Users/doosti/OneDrive - Chapman University/Research/Research Projects/Fitness/Data/

In [3]:
comments_day = pd.read_csv(Path + "channel_day_scores_010324.csv")
print(comments_day.shape)
print(comments_day.head())

(48673, 9)
            creator_id        date  Competence  Appearance   Fitness  \
0  262h9yTG1f03Nobo501  2020-11-05    0.000000    0.000000  0.000000
1  262h9yTG1f03Nobo501  2020-11-11    0.470194    0.192258  0.846807
2  262h9yTG1f03Nobo501  2020-11-12    0.437437    0.000000  0.000000
3  262h9yTG1f03Nobo501  2020-11-13    0.000000    0.354054  0.000000
4  262h9yTG1f03Nobo501  2020-11-14    0.203973    0.352136  0.820903

   Enjoyment    Social  no_comments  no_users
0   0.000000  0.000000            1         1
1   0.000000  0.313390           28        28
2   0.000000  0.324201           46        41
3   0.304512  0.152543           42        36
4   0.322645  0.000000           46        36

In [4]:
# loading the raw comment data
comments = pd.read_csv(Path + "labeled_comments_scores_030124.csv")
print(comments.shape)
print(comments.head())

(827552, 16)
      video_id                   user_id  \
0  YxySUy2jU_s  UCLqs5JoktNvfrQZimZ8Gl5g
1  YxySUy2jU_s  UCLqs5JoktNvfrQZimZ8Gl5g
2  YxySUy2jU_s  UCLMqrKUz0vnpsM0haZmHmQA
3  YxySUy2jU_s  UCASrUw6lnbPK4p5plkVFtqw
4  YxySUy2jU_s  UCspkSCEGRikNmsoRGJwG1MQ

                                        comment_text  no_likes  no_replies  \
0  I loved doing this video with my dad I think i...       8.0         0.0
1             bre is very good at yoga same with Flo      10.0         0.0
2  Of course I can add 15 more minutes to round o...       7.0         0.0
3  Thanks for helping round out my routine, was q...       5.0         0.0
4          First thing tomorrow morning! Thank you üôè       2.0         0.0

   comment_year  comment_month  comment_day  Appearance  Enjoyment  Fitness  \
0          2021              4           13         0.0        0.0      0.0
1          2021              4           13         0.0        0.0      0.0
2          2021              4           13         0.0        0.0      0.0
3          2021              4           13         0.0        0.0      0.0
4          2021              4           13         0.0        0.0      0.0

   Competence  Social  max_score  label        date
0         0.0     0.0        0.0  other  2021-04-13
1         0.0     0.0        0.0  other  2021-04-13
2         0.0     0.0        0.0  other  2021-04-13
3         0.0     0.0        0.0  other  2021-04-13
4         0.0     0.0        0.0  other  2021-04-13

In [5]:
# loading videos for creator id
videos = pd.read_csv(os.path.join(Path, "videos_101223.csv"))

In [6]:
videos.head()

,video_id,title,creator,creator_id,publish_date,duration,v1,v2,v3,v7,...,e7,e30,views,enagement,likes,shares,comments,keywords,topics,challenge
0,fK5-vlRS32I,30 min Minimal Cues Coffee Cup Interval Yoga -...,Ali Kamenova Yoga,WW832gM4hx,2020-10-14,4880,856.0,1101.0,1250.0,1722.0,...,94.0,116.0,5378,163,146.0,NaN,17.0,"['Lifestyle', 'Physical fitness']","['morning yoga', 'yoga at home', 'online yoga'...",False
1,dW5eqwJpFbg,Q&A from instagram,Ali Kamenova Yoga,WW832gM4hx,2020-10-19,3673,542.0,677.0,750.0,998.0,...,77.0,103.0,2887,123,107.0,NaN,16.0,"['Technology', 'Lifestyle']",[],False
2,_LDGDKcweVQ,Skin Care & Makeup,Ali Kamenova Yoga,WW832gM4hx,2020-10-31,2412,428.0,611.0,695.0,888.0,...,53.0,75.0,2316,97,78.0,NaN,19.0,['Lifestyle'],[],False
3,wK_S9jB2P4Q,Somatic Pelvic Integrity Mula Bandha Yoga Cla...,Ali Kamenova Yoga,WW832gM4hx,2020-11-16,4022,NaN,1317.0,1527.0,2041.0,...,121.0,154.0,6675,231,214.0,NaN,17.0,"['Physical fitness', 'Lifestyle']","['morning yoga', 'yoga at home', 'online yoga'...",False
4,RZafnNgCZU8,"Psoas Massage Tool PSO-RITE for Sciatica, Lowe...",Ali Kamenova Yoga,WW832gM4hx,2020-11-22,882,635.0,804.0,914.0,1117.0,...,40.0,52.0,6643,122,115.0,NaN,7.0,"['Physical fitness', 'Lifestyle']","['morning yoga', 'yoga at home', 'online yoga'...",False

In [13]:
# TEMP
# merging the challenge information to test hypotheses
comments_stats = comments.merge(videos, on='video_id', how='left')
grouped_commets = comments_stats.groupby('video_id').agg({'user_id':'count','challenge':'first'})
print(grouped_commets.head())
print(grouped_commets.groupby('challenge').agg({'user_id':'mean'}))

             user_id challenge
video_id
--hIRLygKXA        4     False
--jPJL2cymY       50     False
-06jjaDlHFA       28     False
-0PaX_5WXNA      228     False
-1-0BGCmHps       27     False
              user_id
challenge
False       52.932308
True       135.701375

In [10]:
comments['creator_id'] = comments.merge(videos,how='left',on='video_id').creator_id.values
comments = comments.dropna(subset=['creator_id'])
comments.isnull().sum()

video_id         0
user_id          0
comment_text     0
no_likes         0
no_replies       0
comment_year     0
comment_month    0
comment_day      0
Appearance       0
Enjoyment        0
Fitness          0
Competence       0
Social           0
max_score        0
label            0
date             0
creator_id       0
dtype: int64

In [12]:
grouped = comments.groupby(['creator_id','date'])[['no_likes','no_replies']].sum().reset_index()
print(grouped.head())
comments_day = comments_day.merge(grouped,how='left',on=['creator_id','date'])
print(comments_day.head())

            creator_id        date  no_likes  no_replies
0  262h9yTG1f03Nobo501  2020-11-05       1.0         0.0
1  262h9yTG1f03Nobo501  2020-11-11      44.0         9.0
2  262h9yTG1f03Nobo501  2020-11-12      27.0        20.0
3  262h9yTG1f03Nobo501  2020-11-13      50.0        12.0
4  262h9yTG1f03Nobo501  2020-11-14      49.0        22.0
            creator_id        date  Competence  Appearance   Fitness  \
0  262h9yTG1f03Nobo501  2020-11-05    0.000000    0.000000  0.000000
1  262h9yTG1f03Nobo501  2020-11-11    0.470194    0.192258  0.846807
2  262h9yTG1f03Nobo501  2020-11-12    0.437437    0.000000  0.000000
3  262h9yTG1f03Nobo501  2020-11-13    0.000000    0.354054  0.000000
4  262h9yTG1f03Nobo501  2020-11-14    0.203973    0.352136  0.820903

   Enjoyment    Social  no_comments  no_users  no_likes  no_replies
0   0.000000  0.000000            1         1       1.0         0.0
1   0.000000  0.313390           28        28      44.0         9.0
2   0.000000  0.324201           46        41      27.0        20.0
3   0.304512  0.152543           42        36      50.0        12.0
4   0.322645  0.000000           46        36      49.0        22.0

In [14]:
# adding likes and replies for the competence
grouped = comments[comments.label=="Competence"].groupby(['creator_id','date'])[['no_likes','no_replies']].sum().reset_index()
# changing the column names
grouped.columns = ['creator_id','date','competence_likes','competence_replies']
comments_day = comments_day.merge(grouped,how='left',on=['creator_id','date'])
# adding likes and replies for the social
grouped = comments[comments.label=="Social"].groupby(['creator_id','date'])[['no_likes','no_replies']].sum().reset_index()
# changing the column names
grouped.columns = ['creator_id','date','social_likes','social_replies']
comments_day = comments_day.merge(grouped,how='left',on=['creator_id','date'])
print(comments_day.head())

            creator_id        date  Competence  Appearance   Fitness  \
0  262h9yTG1f03Nobo501  2020-11-05    0.000000    0.000000  0.000000
1  262h9yTG1f03Nobo501  2020-11-11    0.470194    0.192258  0.846807
2  262h9yTG1f03Nobo501  2020-11-12    0.437437    0.000000  0.000000
3  262h9yTG1f03Nobo501  2020-11-13    0.000000    0.354054  0.000000
4  262h9yTG1f03Nobo501  2020-11-14    0.203973    0.352136  0.820903

   Enjoyment    Social  no_comments  no_users  no_likes  no_replies  \
0   0.000000  0.000000            1         1       1.0         0.0
1   0.000000  0.313390           28        28      44.0         9.0
2   0.000000  0.324201           46        41      27.0        20.0
3   0.304512  0.152543           42        36      50.0        12.0
4   0.322645  0.000000           46        36      49.0        22.0

   competence_likes  competence_replies  social_likes  social_replies
0               NaN                 NaN           NaN             NaN
1               NaN                 NaN           NaN             NaN
2               NaN                 NaN           NaN             NaN
3               NaN                 NaN           NaN             NaN
4               NaN                 NaN           NaN             NaN

In [15]:
comments_day.describe()

,Competence,Appearance,Fitness,Enjoyment,Social,no_comments,no_users,no_likes,no_replies,competence_likes,competence_replies,social_likes,social_replies
count,48673.000000,48673.000000,48673.000000,48673.000000,48673.000000,48673.000000,48673.000000,48673.000000,48673.000000,517.000000,517.000000,115.000000,115.000000
mean,0.087281,0.072051,0.109649,0.105745,0.055110,16.625665,15.952664,44.681096,5.809628,1.166344,0.375242,13.173913,0.356522
std,0.473433,0.277708,0.434126,0.526606,0.329539,62.643429,60.335956,509.506708,26.187234,4.342796,0.694947,86.121116,1.452109
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,5.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,13.000000,10.000000,5.000000,1.000000,1.000000,1.000000,0.000000
max,25.100176,13.634835,21.356962,29.209454,20.561265,3262.000000,3175.000000,26123.000000,1161.000000,50.000000,5.000000,680.000000,12.000000

In [16]:
comments_day.fillna(0).to_csv(Path + "channel_day_scores_042724.csv",index=False)